AvansFysioApp/Controllers/PatientfileController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AvansFysioApp.ExtentionMethods;
using AvansFysioAppDomain.Domain;
using AvansFysioAppDomainServices.DomainServices;
using AvansFysioAppDomainServices.Validation;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AvansFysioApp.Controllers
{
    public class PatientfileController : Controller
    {

        private IRepo repository;
        private PatientFileIRepo fileRepository;
        private IPhysiotherapistRepo physiotherapistRepo;
        private TreatmentPlanIRepo treatmentPlanIRepo;
        private TreatmentIRepo treatmentIRepo;
        private UserManager<IdentityUser> userManager;
        private OperationIRepo operationIRepo;
        private RemarkIRepo remarkIRepo;
        private PatientValidation patientValidation;

        public PatientfileController(IRepo repository, RemarkIRepo remarkIRepo, PatientFileIRepo fileRepository, IPhysiotherapistRepo physiotherapistRepo, TreatmentPlanIRepo treatmentPlanIRepo, TreatmentIRepo treatmentIRepo, OperationIRepo operationIRepo, UserManager<IdentityUser> userManager)
        {
            this.repository = repository;
            this.fileRepository = fileRepository;
            this.physiotherapistRepo = physiotherapistRepo;
            this.remarkIRepo = remarkIRepo;
            this.operationIRepo = operationIRepo;
            this.treatmentIRepo = treatmentIRepo;
            this.treatmentPlanIRepo = treatmentPlanIRepo;
            this.userManager = userManager;
            patientValidation = new PatientValidation();
        }

        public void AddPatientsInViewbag()
        {
            var patients = repository.Patients().Prepend(new Patient() { PatientId = -1, Name = "Select a patient" });
            ViewBag.Patients = new SelectList(patients, "PatientId", "Name");
        }

        public void AddPatientFilesInViewbag()
        {
            var patientFiles = fileRepository.Responses().Prepend(new PatientFile() { Id = -1, Title = "Select a patient" });
            ViewBag.PatientFiles = new SelectList(patientFiles, "Id", "Title");
        }

        public void AddPatientFilesWithoutTreatmentInViewbag()
        {
            List<PatientFile> list = new List<PatientFile>();
            foreach (PatientFile patientFile in fileRepository.Responses())
            {
                var tp = treatmentPlanIRepo.FindTreatmentPlanWithPatientFile(patientFile.Id);
                if (tp == null)
                {
                    list.Add(patientFile);
                }
            }
            var patientFiles = list.Prepend(new PatientFile() { Id = -1, Title = "Select a patient" });
            ViewBag.PatientFiles = new SelectList(patientFiles, "Id", "Title");
        }

        public void AddPhysioToList()
        {
            ViewBag.Physio = physiotherapistRepo.Physiotherapists();
        }
        public void AddPatientToList()
        {
            ViewBag.Pat = repository.Patients();
        }

        public void AddPhysiotherapistsInViewbag()
        {
            var physios = physiotherapistRepo.Physiotherapists().Prepend(new Physiotherapist() { Id = -1, Name = "Select a physiotherapist" });
            ViewBag.Physiotherapists = new SelectList(physios, "Id", "Name");
        }

        public void AddPhysiotherapistsExceptInternInViewbag()
        {

            List<Physiotherapist> noIntern = new List<Physiotherapist>();

            foreach (Physiotherapist p in physiotherapistRepo.Physiotherapists())
            {
                if (!p.IsIntern)
                {
                    noIntern.Add(p);
                }
            }

            var physios = noIntern.Prepend(new Physiotherapist() { Id = -1, Name = "Select a physiotherapist" });
            ViewBag.NoIntern = new SelectList(physios, "Id", "Name");
        }

        public void AddPatientsWithNoPatientFile()
        {
            List<Patient> list = new List<Patient>();
            foreach (var p in repository.Patients())
                if (fileRepository.FindFileWithPatientId(p.PatientId) == null) list.Add(p);
            ViewBag.PatientNoFile = new SelectList(list, "PatientId", "Name");
        }

        public List<Treatment> AddTreatmentsToListByPatientFile(int id)
        {
            List<Treatment> list = new List<Treatment>();
            foreach (Treatment treatment in treatmentIRepo.Treatments().Where((x) => x.PatientFileId == id))
            {
                list.Add(treatment);
            }
            return list;
        }

        public void AddRemarksOfFileToViewBag(int id)
        {
            var list = remarkIRepo.GetRemarksByFile(id);
            ViewBag.Remarks = list;
        }

        [Authorize(Policy = "InternOrPhysioOnly")]
        [HttpGet]
        public ActionResult AddFileView()
        {
            AddPhysioToList();
            AddPatientToList();
            AddPhysiotherapistsInViewbag();
            AddPatientsWithNoPatientFile();
            AddPhysiotherapistsExceptInternInViewbag();
            return View();
        }

        [Authorize(Policy = "InternOrPhysioOnly")]
        [HttpPost]
        public async Task<ActionResult> AddFileView(PatientFile patientFile)
        {
            AddPhysioToList();
            AddPatientToList();
            AddPatientsWithNoPatientFile();
            AddPhysiotherapistsInViewbag();
            AddPhysiotherapistsExceptInternInViewbag();
            if (ModelState.IsValid)
            {
                if (patientFile.SupervisionById == -1 || patientFile.HeadPractitionerId == -1 || patientFile.DateOfRegister > DateTime.Now || patientFile.DateOfEnd < DateTime.Now)
                {
                    if (patientFile.SupervisionById == -1)
                    {
                        ModelState.AddModelError("", "Please select a supervisor.");
                    }

                    if (patientFile.HeadPractitionerId == -1)
                    {
                        ModelState.AddModelError("", "Head practitioner is required!");
                    }

                    if (patientFile.DateOfRegister > DateTime.Now)
                    {
                        ModelState.AddModelError("", "Date of register cannot be in the future!");
                    }
                    if (patientFile.DateOfEnd < DateTime.Now)
                    {
                        ModelState.AddModelError("", "Date of firing must be in the future!");
                    }
                    return View(patientFile);
                }
                if (patientFile.PatientId != null)
                {
                    Patient patient = repository.GetPatient((int)patientFile.PatientId);
                    patientFile.Age = patient.GetAge();
                    patientFile.Title = patient.Name;
                }

                var user = await userManager.GetUserAsync(User);
                Physiotherapist p = physiotherapistRepo.getPhysiotherapistByEmail(user.Email);
                patientFile.IntakeById = p.Id;
                
                repository.Patients();
                TempData.Put("patientFile", patientFile);
                return RedirectToAction("FindDiagnosis", "Home");

            }
            AddPhysioToList();
            AddPatientToList();
            AddPhysiotherapistsInViewbag();
            AddPhysiotherapistsExceptInternInViewbag();
            return View(patientFile);
        }

        [Authorize(Policy = "InternOrPhysioOnly")]
        [HttpGet]
        public ActionResult UpdateFileView(int id)
        {
            AddPhysioToList();
            AddPatientToList();
            AddPatientsInViewbag();
            AddPhysiotherapistsInViewbag();
            AddPhysiotherapistsExceptInternInViewbag();

            PatientFile patientFile = fileRepository.GetPatientFile(id);
            return View(patientFile);
        }

        [Authorize(Policy = "InternOrPhysioOnly")]
        [HttpPost]
        public ActionResult UpdateFileView(PatientFile patientFile)
        {
            AddPhysioToList();
            AddPatientToList();
            AddPatientsInViewbag();
            AddPhysiotherapistsInViewbag();
            AddPhysiotherapistsExceptInternInViewbag();
            if (ModelState.IsValid)
            {
                Physiotherapist physiotherapist = physiotherapistRepo.GetPhysiotherapist((int)patientFile.IntakeById) ?? null;

                if (physiotherapist == null || (physiotherapist.IsIntern && patientFile.SupervisionById == -1) || patientFile.HeadPractitionerId == -1 || patientFile.DateOfEnd < DateTime.Now)
                {
                    if (physiotherapist == null)
                    {
                        ModelState.AddModelError("", "Intake by is required!.");
                        return View(patientFile);
                    }

                    if (patientFile.HeadPractitionerId == -1)
                    {
                        ModelState.AddModelError("", "Head practitioner is required!");
                    }

                    if (physiotherapist.IsIntern && patientFile.SupervisionById == -1)
                    {
                        ModelState.AddModelError("", "Supervision is required while taking an intake as an intern.");
                    }
                    if (patientFile.DateOfEnd < DateTime.Now)
                    {
                        ModelState.AddModelError("", "Date of firing must be in the future!");
                    }
                    return View(patientFile);
                }

                if (patientFile.SupervisionById == -1)
                {
                    patientFile.SupervisionById = null;
                }
                repository.Patients();
                fileRepository.UpdatePatientFile(patientFile);

AvansFysioApp/Views/Patientfile/AddFileView.cshtml
@using System.Security.Claims
@model AvansFysioAppDomain.Domain.PatientFile
@{
    var identity = (ClaimsIdentity)User.Identity;
    IEnumerable<Claim> claims = identity.Claims;
    
    var claimInt = claims.FirstOrDefault(x => x.Value == "Intern");
}

<form asp-controller="Patientfile" asp-action="AddFileView" method="post" class="m-2">

    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="PatientId">Patient:</label>
        <select class="form-control" asp-for="PatientId" asp-items="@ViewBag.PatientNoFile"></select>
    </div>
    <div class="form-group">
        <label asp-for="DescriptionComplaintsGlobal">DescriptionComplaintsGlobal:</label>
        <input asp-for="DescriptionComplaintsGlobal" class="form-control" />
    </div>
    
    @if (claimInt != null)
    {
        <div class="form-group">
            <label asp-for="SupervisionById">Supervision by:</label>
            <select class="form-control" asp-for="SupervisionById" asp-items="@ViewBag.NoIntern" required></select>
        </div>
    }
    
    <div class="form-group">
        <label asp-for="DateOfRegister">Date of registration:</label>
        <input class="form-control" asp-for="DateOfRegister" type="date" />
    </div>
    <div class="form-group">
        <label asp-for="DateOfEnd">Date of firing:</label>
        <input class="form-control" asp-for="DateOfEnd" type="date" />
    </div>

    <div class="form-group">
        <label asp-for="HeadPractitionerId">HeadPractitioner:</label>
        <select class="form-control" asp-for="HeadPractitionerId" asp-items="@ViewBag.Physiotherapists" required></select>
    </div>

    <button type="submit" class="btn btn-primary">Add patient</button>
    <a asp-controller="Patient" asp-action="PatientList" class="btn btn-secondary">Cancel</a>
</form>

AvansFysioApp/Views/Patientfile/AddRemark.cshtml
@model AvansFysioAppDomain.Domain.Remark

<h2>Add remark</h2>


<form asp-controller="Patientfile" asp-action="AddRemark" method="post" class="m-2">

    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="FileByRemarkId">Patient:</label>
        <select class="form-control" asp-for="FileByRemarkId" asp-items="@ViewBag.PatientFiles"></select>
    </div>
    <div class="form-group">
        <label asp-for="Note">Note:</label>
        <input class="form-control" asp-for="Note" />
    </div>
    <div class="form-group">
        <label asp-for="SeenByPatient">Seen by patient:</label>
        <input type="checkbox" asp-for="SeenByPatient" class="form-control" style="float: left" />
    </div>

    <button type="submit" class="btn btn-primary">Add session</button>
    <a asp-controller="Patient" asp-action="PatientList" class="btn btn-secondary">Cancel</a>
</form>

AvansFysioApp/Views/Patientfile/AddTreatment.cshtml
@model AvansFysioAppDomain.Domain.Treatment

<h2>Add treatment</h2>

<form asp-controller="Patientfile" asp-action="AddTreatment" method="post" class="m-2">

    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="PatientFileId">Patient:</label>
        <select class="form-control" asp-for="PatientFileId" asp-items="@ViewBag.PatientFiles"></select>
    </div>

    <div class="form-group">
        <label asp-for="Room">Room:</label>
        <select asp-for="Room" class="form-control">
            <option value="">Select an occupation</option>
            <option value="Practice room">Practice room</option>
            <option value="Treatment room">Treatment room</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="DateOfTreatment">Date of treatment:</label>
        <input asp-for="DateOfTreatment" class="form-control" type="Date"/>
    </div>
    
    <div class="form-group">
        <label asp-for="Particularities">Particularities:</label>
        <input asp-for="Particularities" class="form-control"/>
    </div>
    
    <div class="form-group">
        <label asp-for="PhysiotherapistId">Physiotherapist:</label>
        <select class="form-control" asp-for="PhysiotherapistId" asp-items="@ViewBag.Physiotherapists"></select>
    </div>

    <button type="submit" class="btn btn-primary">Next</button>
    <a asp-controller="Home" asp-action="FindOperation" class="btn btn-secondary">Cancel</a>
</form>

AvansFysioApp/Views/Patientfile/AddTreatmentPlan.cshtml
@model AvansFysioAppDomain.Domain.TreatmentPlan
<form asp-controller="Patientfile" asp-action="AddTreatmentPlan" method="post" class="m-2">

    <div asp-validation-summary="All" class="text-danger"></div>
    
    <div class="form-group">
        <label asp-for="FileId">Patient:</label>
        <select class="form-control" asp-for="FileId" asp-items="@ViewBag.PatientFiles"></select>
    </div>
    
    <div class="form-group">
        <label asp-for="Title">Title</label>
        <input class="form-control" asp-for="Title"/>
    </div>

    <div class="form-group">
        <label asp-for="MaxSessions">Max sessions per week:</label>
        <input type="number" class="form-control" asp-for="MaxSessions"/>
    </div>

    <div class="form-group">
        <label asp-for="Duration">Duration of a session in minutes:</label>
        <input type="number" class="form-control" asp-for="Duration"/>
    </div>

    <button type="submit" class="btn btn-primary">Add patient</button>
    <a asp-controller="Patient" asp-action="PatientList" class="btn btn-secondary">Cancel</a>
</form>

AvansFysioApp/Views/Patientfile/EditTreatment.cshtml
@model AvansFysioAppDomain.Domain.Treatment

<h2>Edit treatment</h2>

<form asp-controller="Patientfile" asp-action="EditTreatment" method="post" class="m-2">

    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" asp-for="PatientFileId"/>
    <input type="hidden" asp-for="DateCreated"/>
    <input type="hidden" asp-for="TypeId"/>
    <input type="hidden" asp-for="Description"/>
        
    <div class="form-group">
        <label asp-for="Room">Room:</label>
        <select asp-for="Room" class="form-control">
            <option value="">Select an occupation</option>
            <option value="Practice room">Practice room</option>
            <option value="Treatment room">Treatment room</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="DateOfTreatment">Date of treatment:</label>
        <input asp-for="DateOfTreatment" class="form-control" type="Date" />
    </div>

    <div class="form-group">
        <label asp-for="Particularities">Particularities:</label>
        <input asp-for="Particularities" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="PhysiotherapistId">Physiotherapist:</label>
        <select class="form-control" asp-for="PhysiotherapistId" asp-items="@ViewBag.Physiotherapists"></select>
    </div>

    <button type="submit" class="btn btn-primary">Save</button>
    <a asp-controller="Patientfile" asp-action="TreatmentView" asp-route-id="@Model.PatientFileId" class="btn btn-secondary">Cancel</a>
</form>

AvansFysioApp/Views/Patientfile/TreatmentView.cshtml
@using AvansFysioAppDomain.Domain
@model List<AvansFysioAppDomain.Domain.Treatment>
    <h2>Treatments</h2>

    @foreach (Treatment treatment in Model)
    {
        <div class="textBlocks2">
            <table style="width: 100%">
                <tr>
                    <th>Description:</th>
                    <td>@treatment.Description</td>
                </tr>
                <tr>
                    <th>Date of treatment:</th>
                    <td>@treatment.DateOfTreatment.ToShortDateString()</td>
                </tr>
                <tr>
                    <th>Date treatment added:</th>
                    <td>@treatment.DateCreated.ToShortDateString()</td>
                </tr>
                @if (treatment.Particularities != null)
                {
                    <tr>
                        <th>Particularities:</th>
                        <td>@treatment.Particularities</td>
                    </tr>
                }
                <tr>
                    <th>Treatment:</th>
                    <td>@treatment.TypeId</td>
                </tr>
                <tr>
                    <th>Room:</th>
                    <td>@treatment.Room</td>
                </tr>
                @if (treatment.DateCreated.ToString("dd-MM-yyyy") == DateTime.Now.ToString("dd-MM-yyyy") && ViewBag.IsPatient == null)
                {
                    <tr>
                        <th></th>
                        <td><a asp-controller="Patientfile" asp-action="EditTreatment" asp-route-id="@treatment.Id">Edit treatment</a> | <a asp-controller="Patientfile" asp-action="DeleteTreatment" asp-route-id="@treatment.Id">Delete treatment</a></td>
                    </tr>
                }
            </table>
        </div>
    }
@if (ViewBag.Id != null)
{
    <a asp-controller="Patient" asp-action="DetailView" asp-route-id="@ViewBag.Id" class="btn btn-secondary">Patient details</a>
}

AvansFysioApp/Views/Patientfile/UpdateFileView.cshtml
@using AvansFysioAppDomain.Domain
@using System.Security.Claims
@model PatientFile
@{
    var identity = (ClaimsIdentity)User.Identity;
    IEnumerable<Claim> claims = identity.Claims;

    var claimInt = claims.FirstOrDefault(x => x.Value == "Intern");
}

<h2>Update file</h2>

<form asp-controller="Patientfile" asp-action="UpdateFileView" method="post" class="m-2">

    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <input asp-for="PatientId" type="hidden" />
    </div>
    <div class="form-group">
        <input asp-for="Age" class="form-control" type="hidden" />
    </div>

    <input asp-for="Title" type="hidden" />
    <input asp-for="DiagnosisDescription" type="hidden" />
    <input asp-for="DiagnosisNumber" type="hidden" />

    <div class="form-group">
        <label asp-for="DescriptionComplaintsGlobal">DescriptionComplaintsGlobal:</label>
        <input asp-for="DescriptionComplaintsGlobal" class="form-control" />
    </div>

    <div>
        <label asp-for="IntakeById">Intake by:</label>
        <select class="form-control" asp-for="IntakeById" asp-items="@ViewBag.Physiotherapists"></select>
    </div>

    <div class="form-group">
        <label asp-for="SupervisionById">Supervised by:</label>
        <select class="form-control" asp-for="SupervisionById" asp-items="@ViewBag.NoIntern"></select>
    </div>

    <div class="form-group">
        <label asp-for="DateOfRegister">Date of registration:</label>
        <input class="form-control" asp-for="DateOfRegister" type="date" />
    </div>
    
    <div class="form-group">
        <label asp-for="DateOfEnd">Date of firing:</label>
        <input class="form-control" asp-for="DateOfEnd" type="date" />
    </div>

    <div class="form-group">
        <label asp-for="HeadPractitionerId">HeadPractitioner:</label>
        <select class="form-control" asp-for="HeadPractitionerId" asp-items="@ViewBag.Physiotherapists"></select>
    </div>

    <button type="submit" class="btn btn-primary">Save changes</button>
    <a asp-controller="Patient" asp-action="DetailView" asp-route-id="@Model.PatientId" class="btn btn-secondary">Cancel</a>

</form>