AvansFysioApp/Controllers/PatientController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using AvansFysioAppDomain.Domain;
using AvansFysioAppDomainServices.DomainServices;
using Microsoft.AspNetCore.Authorization;

namespace AvansFysioApp.Controllers
{
    public class PatientController : Controller
    {
        private IRepo repository;
        private PatientFileIRepo fileRepository;
        private IPhysiotherapistRepo physiotherapistRepo;
        private TreatmentPlanIRepo treatmentPlanIRepo;
        private TreatmentIRepo treatmentIRepo;
        private SessionIRepo sessionIRepo;
        private RemarkIRepo remarkIRepo;

        public PatientController(IRepo repository, RemarkIRepo remarkIRepo, PatientFileIRepo fileRepository, IPhysiotherapistRepo physiotherapistRepo, TreatmentPlanIRepo treatmentPlanIRepo, TreatmentIRepo treatmentIRepo, SessionIRepo sessionIRepo)
        {
            this.repository = repository;
            this.fileRepository = fileRepository;
            this.physiotherapistRepo = physiotherapistRepo;
            this.remarkIRepo = remarkIRepo;
            this.sessionIRepo = sessionIRepo;
            this.treatmentIRepo = treatmentIRepo;
            this.treatmentPlanIRepo = treatmentPlanIRepo;
        }

        public void AddPhysioToList()
        {
            ViewBag.Physio = physiotherapistRepo.Physiotherapists();
        }

        public void AddPatientToList()
        {
            ViewBag.Pat = repository.Patients();
        }

        public void AddTreatmentsToListByPatientList(int id)
        {
            List<Treatment> list = new List<Treatment>();
            foreach (Treatment treatment in treatmentIRepo.Treatments().Where((x) => x.PatientFileId == id))
            {
                list.Add(treatment);
            }
            ViewBag.Treatments = list;
        }

        public void AddAppointmentsInViewbag(string email)
        {
            Patient patient = repository.GetPatientByEmail(email);
            Physiotherapist physiotherapist = physiotherapistRepo.getPhysiotherapistByEmail(email);
            List<Session> list = new List<Session>();

            if (patient != null)
            {
                foreach (var a in sessionIRepo.Sessions())
                {
                    if (a!= null && a.PatientId == patient.PatientId)
                    {
                        list.Add(a);
                    }
                }
            }
            else if (physiotherapist != null)
            {
                foreach (var a in sessionIRepo.Sessions())
                {
                    if (a != null && a.HeadPhysiotherapistId == physiotherapist.Id)
                    {
                        list.Add(a);
                    }
                }
            }
            ViewBag.AppointmentList = list;
        }

        public void AddRemarksOfFileToViewBag(int id)
        {
            var list = remarkIRepo.GetRemarksByFile(id);
            ViewBag.Remarks = list;
        }


        [Authorize(Policy = "InternOrPhysioOnly")]
        [HttpGet]
        public ActionResult AddPatientView()
        {
            return View();
        }

        [Authorize(Policy = "InternOrPhysioOnly")]
        [HttpPost]
        public ActionResult AddPatientView(PatientViewModel patientViewModel)
        {
            if (ModelState.IsValid)
            {
                if (repository.GetPatientByEmail(patientViewModel.Email) != null | physiotherapistRepo.getPhysiotherapistByEmail(patientViewModel.Email) != null)
                {
                    ModelState.AddModelError("", "Email is already in use.");
                    return View(patientViewModel);
                }

                var patient = new Patient
                {
                    Name = patientViewModel.Name,
                    Email = patientViewModel.Email,
                    Phone = patientViewModel.Phone,
                    Occupation = patientViewModel.Occupation,
                    OccupationId = patientViewModel.OccupationId,
                    Birthday = patientViewModel.Birthday,
                    Gender = patientViewModel.Gender,
                    PictureFormat = patientViewModel.Picture.ContentType
                };
                var memoryStream = new MemoryStream();
                patientViewModel.Picture.CopyTo(memoryStream);
                patient.Picture = memoryStream.ToArray();

                repository.AddPatient(patient);
                return RedirectToAction("DetailView", new { id = patient.PatientId });
            }
            else return View();
        }

        [Authorize(Policy = "InternOrPhysioOnly")]
        [HttpGet]
        public ActionResult EditPatientView(int id)
        {
            AddPhysioToList();
            AddPatientToList();
            Patient patient = repository.GetPatient(id);

            PatientViewModel patientViewModel = new PatientViewModel
            {
                Name = patient.Name,
                Email = patient.Email,
                Phone = patient.Phone,
                Occupation = patient.Occupation,
                OccupationId = patient.OccupationId,
                Birthday = patient.Birthday,
                Gender = patient.Gender,
                PatientId = patient.PatientId
            };

            ViewBag.Pic = Convert.ToBase64String(patient.Picture);
            ViewBag.PicFormat = patient.PictureFormat;


            return View(patientViewModel);
        }

        [Authorize(Policy = "InternOrPhysioOnly")]
        [HttpPost]
        public ActionResult EditPatientView(PatientViewModel patientViewModel)
        {
            if (ModelState.IsValid)
            {
                Patient oldPatient = repository.GetPatient(patientViewModel.PatientId);
                var patient = new Patient
                {
                    PatientId = patientViewModel.PatientId,
                    Name = patientViewModel.Name,
                    Email = patientViewModel.Email,
                    Phone = patientViewModel.Phone,
                    Occupation = patientViewModel.Occupation,
                    OccupationId = patientViewModel.OccupationId,
                    Birthday = patientViewModel.Birthday,
                    Gender = patientViewModel.Gender
                };
                if (patientViewModel.EditedPicture != null)
                {
                    var memoryStream = new MemoryStream();
                    patientViewModel.EditedPicture.CopyTo(memoryStream);
                    patient.Picture = memoryStream.ToArray();
                    patient.PictureFormat = patientViewModel.EditedPicture.ContentType;
                }
                else
                {
                    patient.Picture = oldPatient.Picture;
                    patient.PictureFormat = oldPatient.PictureFormat;
                }


                repository.UpdatePatient(patient);
                return RedirectToAction("DetailView", new { id = patient.PatientId });
            }
            else return View(patientViewModel);
        }

        [Authorize(Policy = "InternOrPhysioOnly")]
        public IActionResult PatientList()
        {
            AddPhysioToList();
            AddPatientToList();
            return View("PatientList", repository.Patients());
        }
        
        [HttpGet]
        public ActionResult DetailView(int id)
        {
            AddPhysioToList();
            AddPatientToList();
            Patient patient = repository.GetPatient(id);
            PatientFile patientFile = fileRepository.FindFileWithPatientId(id);
            AddAppointmentsInViewbag(patient.Email);

            if (patientFile != null)
            {
                AddRemarksOfFileToViewBag(patientFile.Id);
                ViewBag.Tp = treatmentPlanIRepo.GetTreatmentPlan(patientFile.Id);
                AddTreatmentsToListByPatientList(patientFile.Id);
            }

            var viewModel = new PatientDisplayViewModel
            {
                PatientId = patient.PatientId,
                Name = patient.Name,
                Email = patient.Email,
                Phone = patient.Phone,
                Occupation = patient.Occupation,
                OccupationId = patient.OccupationId,
                Birthday = patient.Birthday,
                Gender = patient.Gender
            };
            viewModel.Picture = Convert.ToBase64String(patient.Picture);
            viewModel.PictureFormat = patient.PictureFormat;

            physiotherapistRepo.Physiotherapists();
            treatmentIRepo.Treatments();
            ViewBag.PatientFile = patientFile;
            return View("DetailView", viewModel);
        }
    }
}

AvansFysioApp/Views/Patient/AddPatientView.cshtml
@model AvansFysioAppDomain.Domain.PatientViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<form asp-controller="Patient" asp-action="AddPatientView" enctype="multipart/form-data" method="post" class="m-2">

    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Name">Name:</label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Email">Email:</label>
        <input asp-for="Email" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Phone">Phone number:</label>
        <input asp-for="Phone" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Picture" class="control-label"></label>
        <input required asp-for="Picture" accept="image/*"/>
    </div>
    <div class="form-group">
        <label asp-for="Occupation">Occupation:</label>
        <select asp-for="Occupation" class="form-control">
            <option value="">Select an occupation</option>
            <option value="Student">Student</option>
            <option value="Employee">Employee</option>
        </select>
    </div>
    <div class="form-group">
        <label asp-for="OccupationId">Student or personnel number:</label>
        <input asp-for="OccupationId" type="number" class="form-control" required/>
    </div>
    <div class="form-group">
        <label asp-for="Birthday">Birthday:</label>
        <input asp-for="Birthday" type="date" />
    </div>
    <div class="form-group">
        <label asp-for="Gender">Gender:</label>
        <input asp-for="Gender" class="form-control" />
    </div>

    <button type="submit" class="btn btn-primary">Add patient</button>
    <a asp-controller="Patient" asp-action="PatientList" class="btn btn-secondary">Cancel</a>
</form>

AvansFysioApp/Views/Patient/DetailView.cshtml
@using AvansFysioAppDomain.Domain
@using Castle.Core.Internal
@using AvansFysioApp.ExtentionMethods
@using Microsoft.AspNetCore.Identity
@model PatientDisplayViewModel
@{
    PatientFile pf = ViewBag.PatientFile;
    List<Remark> remarks = ViewBag.Remarks;
    TreatmentPlan treatmentPlan = ViewBag.Tp;
    List<Session> sessions = ViewBag.AppointmentList;
    var allSession = sessions.Where(a => a.PatientId == Model.PatientId && a.AppointmentEnd > DateTime.Now).ToList();
    allSession.Sort((x, y) => x.AppointmentBegin.CompareTo(y.AppointmentBegin));
    List<Treatment> treatments = ViewBag.Treatments;
}
@inject UserManager<IdentityUser> UserManager
@{
    var user = await UserManager.GetUserAsync(User);

    bool IsPatient()
    {
        try
        {
            foreach (Patient p in ViewBag.Pat)
            {
                if (p.Email.Equals(user.Email))
                {
                    return true;
                }
            }
            return false;
        }
        catch
        {
            return false;
        }
    }
}


<div>
<h1>Details @Model.Name</h1>
<div class="textBlocks2">

    <table style="width: 69%; float: right">
        <tr>
            <th>
                <h3>Patient:</h3>
            </th>
            @if (!IsPatient())
            {
                <td><a asp-controller="Patient" asp-action="EditPatientView" asp-route-id="@Model.PatientId">Edit Patient</a></td>
            }
        </tr>
        <tr>
            <th>Name:</th>
            <td>@Model.Name</td>
        </tr>
        <tr>
            <th>Email:</th>
            <td>@Model.Email</td>
        </tr>
        <tr>
            <th>Telephone:</th>
            <td>@Model.Phone</td>
        </tr>
        <tr>
            <th>Occupation:</th>
            <td>@Model.Occupation</td>
        </tr>
        <tr>
            <th>ID:</th>
            <td>@Model.OccupationId</td>
        </tr>
        <tr>
            <th>Birthday:</th>
            <td>@Model.Birthday.Value.ToShortDateString()</td>
        </tr>
        <tr>
            <th>Gender:</th>
            <td>@Model.Gender</td>
        </tr>
    </table>

    <div style="width: 30%;">
        <img style="height: 230px; width:200px " src="data:@Model.PictureFormat;base64,@Model.Picture">
    </div>
</div>

<hr />
@if (pf != null)
{
    <h2>Patient file</h2>
}
<div class="textBlocks2">
    <table style="width: 100%">

        @if (pf != null)
        {
            <tr>
                <th>
                    @if (!IsPatient())
                    {
                        <a asp-controller="Patientfile" asp-action="UpdateFileView" asp-route-id="@pf.Id">Edit patient file</a>
                    }
                </th>
                <td></td>
            </tr>
            <tr>
                <th>Patient:</th>
                <td>@pf.Patient.Name</td>
            </tr>
            <tr>
                <th>Age:</th>
                <td>@pf.Age</td>
            </tr>
            <tr>
                <th>Description complaints:</th>
                <td>@pf.DescriptionComplaintsGlobal</td>
            </tr>
            <tr>
                <th>Diagnosis number:</th>
                <td>@pf.DiagnosisNumber
            </tr>
            <tr>
                <th>Diagnosis description:</th>
                <td>@pf.DiagnosisDescription</td>
            </tr>
            <tr>
                <th>Intake by:</th>
                <td>@pf.IntakeBy.Name</td>
            </tr>
            @if (@pf.SupervisionBy != null)
            {
                <tr>
                    <th>Head Supervision by:</th>
                    <td>@pf.SupervisionBy.Name</td>
                </tr>
            }
            <tr>
                <th>Head practitioner:</th>
                <td>@pf.HeadPractitioner.Name</td>
            </tr>
            <tr>
                <th>Date of register:</th>
                <td>@pf.DateOfRegister.ToShortDateString()</td>
            </tr>

            <tr>
                <th>End date:</th>

                @if (@pf.DateOfEnd != null)
                {
                    <td>@pf.DateOfEnd.Value.ToShortDateString()</td>
                }
                else
                {
                    <td>-</td>
                }
            </tr>
            @if (!treatments.IsNullOrEmpty())
            {
                @for (int i = 0; i < treatments.Count; i++)
                {
                    if (i == 0)
                    {
                        <tr>
                            <th>Treatments:</th>
                            <td>@treatments[i].Description</td>
                        </tr>
                        continue;
                    }
                    <tr>
                        <th></th>
                        <td>@treatments[i].Description</td>
                    </tr>
                }
                if (treatments.Count != 0)
                {
                    <tr>
                        <th></th>
                        <td><a asp-controller="Patientfile" asp-action="TreatmentView" asp-route-id="@pf.Id">View all treatments</a></td>
                    </tr>
                }
            }

            @if (!IsPatient())
            {
                <tr>
                    <th><a asp-controller="Home" asp-action="FindOperation" class="btn btn-primary">Add Treatment</a></th>
                </tr>
            }
        }
        <tr>
            <td>
                @if (pf == null)
                {
                    <p>
                        There is no patient file available. <br />
                    </p>

                    @if (!IsPatient())
                    {
                        <a asp-controller="Patientfile" asp-action="AddFileView">Add to a patient file</a>

                    }
                }
            </td>
        </tr>
    </table>
</div>


<hr />

@if (pf != null)
{
    <h2>Remarks</h2>

    if (!remarks.IsNullOrEmpty())
    {

        @foreach (Remark r in remarks)
        {
            @if ((IsPatient() && r.SeenByPatient) || !IsPatient())
            {
                <div class="textBlocks2">
                    <table style="width: 100%">
                        <tr>
                            <th>Note made by:</th>
                            <td>@r.RemarkMadeBy.Name</td>
                        </tr>
                        <tr>
                            <th>Remark:</th>
                            <td>@r.Note</td>
                        </tr>
                        <tr>
                            <th>Placed on:</th>
                            <td>@r.Date</td>
                        </tr>
                        <tr>
                            @if (!IsPatient())
                            {
                                <th>Can be seen by patient:</th>
                                <td>@r.SeenByPatient</td>
                            }
                        </tr>
                    </table>
                </div>
            }
        }
        @if (!IsPatient())
        {
            <div class="textBlocks2">
                <table style="width: 100%">
                    <tr>
                        <th>
                            <a asp-controller="Patientfile" asp-action="AddRemark">Add remark</a>
                        </th>
                    </tr>
                </table>
            </div>
        }

    }
    else
    {
        <div class="textBlocks2">
            There are no remarks available. <br />
            @if (!IsPatient())
            {
                <a asp-controller="Patientfile" asp-action="AddRemark">Add remark</a>
            }
        </div>
    }
    <hr />

}

@if (pf != null)
{
    <h2>Treatment plan</h2>

    if (treatmentPlan != null)
    {
        <div class="textBlocks2">
            <table width="100%">
                <tr>
                    <th>Title:</th>
                    <td>@treatmentPlan.Title</td>
                </tr>
                <tr>
                    <th>Duration:</th>
                    <td>@treatmentPlan.Duration minutes</td>
                </tr>
                <tr>
                    <th>Amount of sessions:</th>
                    <td>@treatmentPlan.MaxSessions sessions a week</td>
                </tr>
            </table>
        </div>
    }
    else
    {
        <div class="textBlocks2">
            There are no treatment plan available. <br />
            @if (!IsPatient())
            {
                <a asp-controller="Patientfile" asp-action="AddTreatmentPlan">Add treatment plan</a>
            }

        </div>
    }
    <hr />
}

@if (pf != null && treatmentPlan != null)
{
    <h2>Appointments</h2>
    @if (!allSession.Any())
    {
        <div class="textBlocks2">
            There are no appointments available. <br />
            <a asp-controller="Appointment" asp-action="AddSession">Add appointment</a>
        </div>
    }

    else
    {
        @foreach (Session a in allSession)
        {
            <div class="textBlocks2">
                <table width="100%">
                    <tr>
                        <th>Physiotherapist:</th>
                        <td>@a.HeadPhysiotherapist.Name</td>
                    </tr>
                    <tr>
                        <th>Start:</th>
                        <td>@a.AppointmentBegin</td>
                    </tr>
                    <tr>
                        <th>End:</th>
                        <td>@a.AppointmentEnd</td>
                    </tr>
                    @if (a.AppointmentBegin.AddHours(-24) >= DateTime.Now)
                    {
                        <tr>
                            <th></th>
                            <td><a asp-controller="Appointment" asp-action="EditSession" asp-route-id="@a.Id">Edit appointment</a> | <a asp-controller="Appointment" asp-action="DeleteSession" asp-route-returnUrl="Patient/DetailView/@pf.PatientId" asp-route-id="@a.Id">Delete appointment</a></td>
                        </tr>
                    }
                </table>
            </div>
        }
        <div class="textBlocks2">
            <a asp-controller="Appointment" asp-action="AddSession">Add appointment</a>
        </div>


    }
}
</div>

AvansFysioApp/Views/Patient/EditPatientView.cshtml
@using AvansFysioAppDomain.Domain
@model PatientViewModel

<form asp-controller="Patient" asp-action="EditPatientView" enctype="multipart/form-data" method="post" class="m-2">

    <div asp-validation-summary="All" class="text-danger"></div>

    <div style="width: 30%;">
        <img style="height: 230px; width:200px " src="data:@ViewBag.PicFormat;base64,@ViewBag.Pic">
    </div>
    <div class="form-group">
        <label asp-for="EditedPicture" class="control-label">Change picture:</label><br />
        <input asp-for="EditedPicture" />
        <p style="font-size: 10px">*Leave empty if you don't want to change.</p>
    </div>
    <div class="form-group">
        <input asp-for="Picture" accept="image/*" type="hidden" />
    </div>
    <div class="form-group">
        <input asp-for="PatientId" type="hidden" />
    </div>
    <div class="form-group">
        <input asp-for="PatientId" class="form-control" type="hidden">
    </div>
    <div class="form-group">
        <label asp-for="Name">Name:</label>
        <input asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <input type="hidden" asp-for="Email" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="Phone">Phone number:</label>
        <input asp-for="Phone" class="form-control" />
    </div>
    <div class="form-group">
        <div class="form-group">
            <label asp-for="Occupation">Occupation:</label>
            <select asp-for="Occupation" class="form-control">
                <option value="">Select an occupation</option>
                <option value="Student">Student</option>
                <option value="Employee">Employee</option>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="OccupationId">Student or personnel number:</label>
        <input asp-for="OccupationId" type="number" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="Birthday">Birthday:</label>
        <input asp-for="Birthday" type="date" />
    </div>
    <div class="form-group">
        <label asp-for="Gender">Gender:</label>
        <input asp-for="Gender" class="form-control" />
    </div>

    <button type="submit" class="btn btn-primary">Save changes</button>
    <a asp-controller="Patient" asp-action="DetailView" asp-route-id="@Model.PatientId" class="btn btn-secondary">Cancel</a>
</form>

AvansFysioApp/Views/Patient/PatientList.cshtml
@using AvansFysioAppDomain.Domain
@model IEnumerable<AvansFysioAppDomain.Domain.Patient>
<div class="text-center p-2">
    <h2>Here is the list of patients</h2>
    <div style="float: right">
    </div>
    <table class="table table-bordered table-striped table-sm">
        <thead>
        <tr><th>Name</th><th>Email</th><th>Phone number</th><th>Occupation</th><th>Student or worker ID</th><th>Birthday</th><th>Gender</th><th><a asp-controller="Patient" asp-action="AddPatientView">Add Patient</a></th></tr>
        </thead>
        <tbody>
        @foreach (Patient p in Model)
        {
            <tr>
                <td>@p.Name</td>
                <td>@p.Email</td>
                <td>@p.Phone</td>
                <td>@p.Occupation</td>
                <td>@p.OccupationId</td>
                <td>@p.Birthday.Value.ToShortDateString()</td>
                <td>@p.Gender</td>
                <td><a asp-controller="Patient" asp-action="EditPatientView" asp-route-id="@p.PatientId">Edit</a> | <a asp-controller="Patient" asp-action="DetailView" asp-route-id="@p.PatientId">Details</a></td>
            </tr>
        }
        </tbody>
    </table>
</div>