AvansFysioApp/Controllers/AppointmentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using AvansFysioAppDomain.Domain;
using AvansFysioAppDomainServices.DomainServices;
using AvansFysioAppDomainServices.Validation;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AvansFysioApp.Controllers
{
    public class AppointmentController : Controller
    {

        private IRepo repository;
        private PatientFileIRepo fileRepository;
        private IPhysiotherapistRepo physiotherapistRepo;
        private TreatmentPlanIRepo treatmentPlanIRepo;
        private SessionIRepo sessionIRepo;
        private UserManager<IdentityUser> userManager;
        private AppointmentValidation appointmentValidation = new AppointmentValidation();

        public AppointmentController(IRepo repository, PatientFileIRepo fileRepository, IPhysiotherapistRepo physiotherapistRepo, TreatmentPlanIRepo treatmentPlanIRepo, SessionIRepo sessionIRepo, UserManager<IdentityUser> userManager)
        {
            this.repository = repository;
            this.fileRepository = fileRepository;
            this.physiotherapistRepo = physiotherapistRepo;
            this.sessionIRepo = sessionIRepo;
            this.treatmentPlanIRepo = treatmentPlanIRepo;
            this.userManager = userManager;
        }

        public void AddPatientsInViewbag()
        {
            var patients = repository.Patients().Prepend(new Patient() { PatientId = -1, Name = "Select a patient" });
            ViewBag.Patients = new SelectList(patients, "PatientId", "Name");
        }

        public void AddPhysioToList()
        {
            ViewBag.Physio = physiotherapistRepo.Physiotherapists();
        }
        public void AddPatientToList()
        {
            ViewBag.Pat = repository.Patients();
        }

        public void AddInternInViewbag()
        {

            List<Physiotherapist> isIntern = new List<Physiotherapist>();

            foreach (Physiotherapist p in physiotherapistRepo.Physiotherapists())
            {
                if (p.IsIntern)
                {
                    isIntern.Add(p);
                }
            }

            var physios = isIntern.Prepend(new Physiotherapist() { Id = -1, Name = "(Optional) Leave empty to choose head practitioner." });
            ViewBag.Intern = new SelectList(physios, "Id", "Name");
        }

        public bool IsIntern(string email)
        {

            Physiotherapist isIntern = new Physiotherapist();

            foreach (Physiotherapist p in physiotherapistRepo.Physiotherapists())
            {
                if (p.Email.Equals(email) && p.IsIntern)
                {
                    return true;
                }
            }

            return false;
        }


        public void AddTreatmentPlanToViewbagByEmail(string email)
        {
            var patient = repository.GetPatientByEmail(email);
            List<TreatmentPlan> list = new List<TreatmentPlan>();

            if (patient != null)
            {
                PatientFile patientFile = fileRepository.FindFileWithPatientId(patient.PatientId);
                TreatmentPlan treatmentPlan = treatmentPlanIRepo.FindTreatmentPlanWithPatientFile(patientFile.Id);
                list.Add(treatmentPlan);
            }
            else
            {
                var physio = physiotherapistRepo.getPhysiotherapistByEmail(email);
                var treatmentPlans = treatmentPlanIRepo.TreatmentPlans();
                foreach (TreatmentPlan treatmentPlan in treatmentPlans)
                {
                    list.Add(treatmentPlan);
                }
            }
            ViewBag.TreatmentPlans = new SelectList(list, "Id", "Title");
        }

        [HttpGet]
        public async Task<IActionResult> AddSession()
        {
            var user = await userManager.GetUserAsync(User);
            AddTreatmentPlanToViewbagByEmail(user.Email);
            AddInternInViewbag();
            ViewBag.IsIntern = IsIntern(user.Email);
            ViewBag.IsPatient = repository.GetPatientByEmail(user.Email);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddSession(Session session)
        {
            AddPhysioToList();
            AddPatientToList();
            AddPatientsInViewbag();
            AddInternInViewbag();
            var user = await userManager.GetUserAsync(User);
            ViewBag.IsPatient = repository.GetPatientByEmail(user.Email);
            ViewBag.IsIntern = IsIntern(user.Email);
            AddTreatmentPlanToViewbagByEmail(user.Email);

            if (ModelState.IsValid)
            {
                TreatmentPlan treatmentPlan = treatmentPlanIRepo.GetTreatmentPlan(session.TreatmentPlanId);
                int size = 0;
                PatientFile patientFile = fileRepository.GetPatientFile(treatmentPlan.FileId);
                Physiotherapist physiotherapist = physiotherapistRepo.GetPhysiotherapist((int)patientFile.HeadPractitionerId);
                Patient p = repository.GetPatient((int)patientFile.PatientId);

                if (session.HeadPhysiotherapistId == -1 || session.HeadPhysiotherapistId == null)
                {
                    session.HeadPhysiotherapistId = physiotherapist.Id;
                }
                else
                {
                    physiotherapist = physiotherapistRepo.GetPhysiotherapist((int)session.HeadPhysiotherapistId);
                }



                session.AppointmentMade = DateTime.Now;
                session.PatientId = p.PatientId;
                session.AppointmentEnd = session.AppointmentBegin.AddMinutes(treatmentPlan.Duration);

                List<Session> sessions = sessionIRepo.GetSessionsWithTreatmentPlanId(treatmentPlan.Id).ToList();

                bool physiotherapistAvailable = appointmentValidation.PhysioIsAvailable(
                    sessionIRepo.GetSessionsWithPhysiotherapistId(physiotherapist.Id).ToList(), session,
                    physiotherapist);


                if (appointmentValidation.CheckIfSessionsPerWeekWillBeExceeded(session, treatmentPlan.MaxSessions, sessions) || !physiotherapistAvailable || patientFile.DateOfEnd < session.AppointmentEnd)
                {
                    if (appointmentValidation.CheckIfSessionsPerWeekWillBeExceeded(session, treatmentPlan.MaxSessions, sessions))
                    {
                        ModelState.AddModelError("", "The maximum amount of sessions this week have been reached.");
                    }

                    if (!physiotherapistAvailable)
                    {
                        ModelState.AddModelError("", "The physiotherapist is unavailable at this time of the day. This physiotherapist is available between " + physiotherapist.AvailabilityStart.ToString("HH:mm") + " and " + physiotherapist.AvailabilityEnd.AddMinutes(-treatmentPlan.Duration).ToString("HH:mm") + "!");
                    }

                    if (patientFile.DateOfEnd < session.AppointmentEnd)
                    {
                        ModelState.AddModelError("", "Appointment must be set before the date of firing: " + patientFile.DateOfEnd.Value.ToString("dd-MM-yyyy"));
                    }
                    return View(session);
                }

                sessionIRepo.AddSession(session);

                return RedirectToAction("DetailView", "Patient", new { id = p.PatientId });
            }
            return View(session);
        }
        
        public IActionResult DeleteSession(int id, string returnUrl = "Appointment/AppointmentList")
        {
            Session session = sessionIRepo.GetSession(id);
            if (appointmentValidation.CheckHoursBeforeAppointmentDeleteIsNotTwentyFour(session))
            {
                return Redirect("../../" + returnUrl);
            }

            sessionIRepo.DeleteSessionWithSessionId(id);
            return Redirect("../../" + returnUrl);
        }

        [HttpGet]
        public async Task<IActionResult> EditSession(int id)
        {
            var s = sessionIRepo.GetSession(id);
            AddInternInViewbag();
            var user = await userManager.GetUserAsync(User);
            ViewBag.IsPatient = repository.GetPatientByEmail(user.Email);
            ViewBag.IsIntern = IsIntern(user.Email);
            return View(s);
        }

        [HttpPost]
        public async Task<IActionResult> EditSession(Session session)
        {
            AddInternInViewbag();
            var user = await userManager.GetUserAsync(User);
            ViewBag.IsPatient = repository.GetPatientByEmail(user.Email);
            ViewBag.IsIntern = IsIntern(user.Email);
            if (ModelState.IsValid)
            {
                var s = sessionIRepo.GetSession(session.Id);
                var treatmentPlan = treatmentPlanIRepo.GetTreatmentPlan(s.TreatmentPlanId);
                int size = 0;

                if (session.HeadPhysiotherapistId == -1 || session.HeadPhysiotherapistId == null)
                {
                    session.HeadPhysiotherapistId = s.HeadPhysiotherapistId;
                }
                else
                {
                    s.HeadPhysiotherapistId = session.HeadPhysiotherapistId;
                }

                Physiotherapist physiotherapist = physiotherapistRepo.GetPhysiotherapist((int)session.HeadPhysiotherapistId);

                int duration = treatmentPlan.Duration;
                s.AppointmentBegin = session.AppointmentBegin;
                session.AppointmentEnd = s.AppointmentBegin.AddMinutes(duration);
                s.AppointmentEnd = s.AppointmentBegin.AddMinutes(duration);

                PatientFile patientFile = fileRepository.GetPatientFile(treatmentPlan.FileId);
                bool physiotherapistAvailable = appointmentValidation.timeOfPhysio(s.AppointmentBegin, s.AppointmentEnd,

AvansFysioApp/Views/Appointment/AddSession.cshtml
@model AvansFysioAppDomain.Domain.Session

    <h2>Add session</h2>


    <form asp-controller="Appointment" asp-action="AddSession" method="post" class="m-2">

        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="TreatmentPlanId">Patient:</label>
            <select class="form-control" asp-for="TreatmentPlanId" asp-items="@ViewBag.TreatmentPlans"></select>
        </div>
        @if (!ViewBag.IsIntern && ViewBag.IsPatient == null)
        {
            <div class="form-group">
                <label asp-for="HeadPhysiotherapistId">Redirect to student:</label>
                <select class="form-control" asp-for="HeadPhysiotherapistId" asp-items="@ViewBag.Intern"></select>
            </div>
        }
        else
        {
            <input type="hidden" asp-for="HeadPhysiotherapistId"/>
        }

        <div class="form-group">
            <label asp-for="AppointmentBegin">Time of appointment:</label>
            <input required="Time of appointment is required" class="form-control" asp-for="AppointmentBegin" asp-format="{0:yyyy-MM-ddTHH:mm}" />
        </div>

        <button type="submit" class="btn btn-primary">Make appointment</button>
        <a asp-controller="Appointment" asp-action="AppointmentList" class="btn btn-secondary">Cancel</a>
    </form>

AvansFysioApp/Views/Appointment/AppointmentList.cshtml
@using AvansFysioAppDomain.Domain
@using Microsoft.AspNetCore.Identity
@model List<AvansFysioAppDomain.Domain.Session>
@{
    bool isPatient = ViewBag.IsPatient;
}

<h2>Appointments</h2>
@if(!isPatient){
    <form asp-controller="Appointment" asp-action="AppointmentList" method="get">
        <p>
            Day of appointment: <input type="date" name="date" />
            <input type="submit" value="Search" />
        </p>
    </form>
}

    @foreach (Session session in @Model)
    {
        <div class="textBlocks2">
            <table style="width: 100%">
                <tr>
                    <th>Patient name:</th>
                    <td>@session.Patient.Name</td>
                </tr>
                <tr>
                    <th>Physiotherapist:</th>
                    <td>@session.HeadPhysiotherapist.Name</td>
                </tr>
                <tr>
                    <th>Date:</th>
                    <td>@session.AppointmentBegin.ToString("dd-MM-yyyy")</td>
                </tr>
                <tr>
                    <th>Time:</th>
                    <td>@session.AppointmentBegin.ToString("HH:mm")-@session.AppointmentEnd.ToString("HH:mm")</td>
                </tr>
                @if (session.AppointmentBegin.AddHours(-24) >= DateTime.Now)
                {
                    <tr>
                        <th></th>
                        <td><a asp-controller="Appointment" asp-action="EditSession" asp-route-id="@session.Id">Edit appointment</a> | <a asp-controller="Appointment" asp-action="DeleteSession" asp-route-returnUrl="Appointment/AppointmentList" asp-route-id="@session.Id">Delete appointment</a></td>
                    </tr>
                }
            </table>
        </div>
    }
    <div class="textBlocks2">
        <a asp-controller="Appointment" asp-action="AddSession">Add appointment</a>
    </div>

AvansFysioApp/Views/Appointment/EditSession.cshtml
@model AvansFysioAppDomain.Domain.Session

<h2>Edit session</h2>


<form asp-controller="Appointment" asp-action="EditSession" method="post" class="m-2">

    <div asp-validation-summary="All" class="text-danger"></div>
    <input type="hidden" asp-for="Id"/>
    @if (!ViewBag.IsIntern && ViewBag.IsPatient == null)
    {
        <div class="form-group">
            <label asp-for="HeadPhysiotherapistId">Redirect to student:</label>
            <select class="form-control" asp-for="HeadPhysiotherapistId" asp-items="@ViewBag.Intern"></select>
        </div>
    }
    else
    {
        <input type="hidden" asp-for="HeadPhysiotherapistId"/>
    }
    <div class="form-group">
        <label asp-for="AppointmentBegin">Time of appointment:</label>
        <input class="form-control" asp-for="AppointmentBegin" asp-format="{0:yyyy-MM-ddTHH:mm}" />
    </div>

    <button type="submit" class="btn btn-primary">Edit appointment</button>
    <a asp-controller="Appointment" asp-action="AppointmentList" class="btn btn-secondary">Cancel</a>
</form>