AvansFysioApp/ViewComponents/AppointmentsViewComponent.cs
using System;
using System.Linq;
using AvansFysioAppDomainServices.DomainServices;
using Microsoft.AspNetCore.Mvc;

namespace AvansFysioApp.ViewComponents

{
    public class AppointmentsViewComponent : ViewComponent
    {
        private SessionIRepo sessionIRepo;

        public AppointmentsViewComponent(SessionIRepo sessionIRepo)
        {
            this.sessionIRepo = sessionIRepo;
        }

        public IViewComponentResult Invoke()
        {
            var amount = sessionIRepo.Sessions().Count(x => x.AppointmentBegin.ToShortDateString() == DateTime.Now.ToShortDateString());
            return View(amount);
        }
    }
}

AvansFysioApp/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using AvansFysioAppDomain.Domain
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@{
    var user = await UserManager.GetUserAsync(User);

    bool IsPhysio()
    {
        try
        {
            foreach (Physiotherapist p in ViewBag.Physio)
            {
                if (p.Email.Equals(user.Email))
                {
                    return true;
                }
            }
            return false;
        }
        catch
        {
            return false;
        }
    }
    bool IsPatient()
    {
        try
        {
            foreach (Patient p in ViewBag.Pat)
            {
                if (p.Email.Equals(user.Email))
                {
                    return true;
                }
            }
            return false;
        }
        catch
        {
            return false;
        }
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AvansFysioApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css?v=@Guid.NewGuid().ToString()" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">AvansFysioApp</a>
                <button class="navbar-toggler bg-info text-white" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="align-self-end">
                    <ul class="navbar-nav flex-grow-1">
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Account" asp-action="LogOut">Logout</a>
                            </li>
                            <li>
                                <a class="nav-link text-white">@user.UserName</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-white">
            &copy; 2021 - AvansFysioApp
            <div style="float: right">@await Component.InvokeAsync("Appointments")</div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>